### ISSUE TITLE
Updates to .Net Core 3.0 Preview 8

### ISSUE THREAD

**Issue by hewhofreeks** [TimeWarpEngineering/blazor-state#162]
Updated to Preview 8 and cannot build my project.  

```
When running I get the following error:
2>Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Void BlazorState.BlazorStateComponent::ReRender()' in assembly: 'BlazorState.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Threading.Tasks.Task Microsoft.AspNetCore.Components.ComponentBase::Invoke(System.Action)
2>   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
2>   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
2>   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
2>   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
2>   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
2>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
```

Most likely due to the fact that `ComponentBase.Invoke` needs to be changed to `ComponentBase.InvokeAsync`
per https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/

Might be other changes that need to be made as well.

**Comment by StevenTCramer** [comment]
Update will be tomorrow
