### ISSUE TITLE
Analyzer 'BlazorStateAnalyzer.BlazorStateActionAnalyzer' threw an exception of type 'System.TypeInitializationException'

### ISSUE THREAD

**Issue by LukePet** [TimeWarpEngineering/blazor-state#355]
In my blazor wasm app, on build I keep getting this warning:

> CSC : warning AD0001: Analyzer 'BlazorStateAnalyzer.BlazorStateActionAnalyzer' threw an exception of type 'System.TypeInitializationException' with message 'The type initializer for 'BlazorStateAnalyzer.BlazorStateActionAnalyzer' threw an exception.'.

I am using the latest version 8.2.4, what's wrong?

![Build Alert](https://github.com/TimeWarpEngineering/blazor-state/assets/6470875/9f95f49a-9866-497a-b8d1-91b7e1cd0dd4)

**Comment by nhwilly** [comment]
It's not you.

I've been working with Steve on this, his recommendation was to punt back to 8.1.0 until it gets sorted out.

I think it started in 8.2.x and 8.2.4 was an attempt to correct it.  It's still doing it for me, too.

I have no idea what happens inside an analyzer, or I'd help.

**Comment by StevenTCramer** [comment]
@LukePet Can you try the latest version. I dropped the CodeAnalysis packages down a version.

**Comment by LukePet** [comment]
I've tested last release 8.2.6 but I keep getting the error. How can i fix it?
The project build successfully, but then on debugging analyzer crashes.
For now I downgraded to 8.1.0.

![Analyzer Crash](https://github.com/TimeWarpEngineering/blazor-state/assets/6470875/dcf49346-9a7c-4294-a03f-89a75b66b48d)
`StreamJsonRpc.RemoteInvocationException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Impossibile trovare il file specificato.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__18`1.MoveNext()
RPC server exception:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Impossibile trovare il file specificato.
      at System.ModuleHandle.ResolveType(QCallModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
      at System.ModuleHandle.ResolveTypeHandle(Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
      at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
      at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctorWithParameters, Boolean& isVarArg)
      at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable)
      at System.Reflection.CustomAttribute.IsDefined(RuntimeType type, RuntimeType caType, Boolean inherit)
      at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat, StringBuilder sb)
      at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
      at System.Exception.get_StackTrace()
      at System.IO.FileNotFoundException.ToString()
      at System.Exception.ToString()
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExceptionDescriptionBuilder.GetExceptionMessage(Exception exception)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExceptionDescriptionBuilder.CreateDiagnosticDescription(Exception exception)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.CreateDiagnosticDescription(Nullable`1 info, Exception e)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.CreateAnalyzerExceptionDiagnostic(DiagnosticAnalyzer analyzer, Exception e, Nullable`1 info)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.AnalyzerExecutionContext.ComputeDiagnosticDescriptors_NoLock(DiagnosticAnalyzer analyzer, AnalyzerExecutor analyzerExecutor)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.AnalyzerExecutionContext.GetOrComputeDescriptors[TDescriptor](ImmutableArray`1& lazyDescriptors, Func`3 computeDescriptorsNoLock, DiagnosticAnalyzer analyzer, AnalyzerExecutor analyzerExecutor, Object gate)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.AnalyzerExecutionContext.GetOrComputeDiagnosticDescriptors(DiagnosticAnalyzer analyzer, AnalyzerExecutor analyzerExecutor)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.IsDiagnosticAnalyzerSuppressed(DiagnosticAnalyzer analyzer, CompilationOptions options, Func`2 isCompilerAnalyzer, AnalyzerExecutor analyzerExecutor, SeverityFilter severityFilter)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.GetAnalyzerActionsAsync(ImmutableArray`1 analyzers, AnalyzerManager analyzerManager, AnalyzerExecutor analyzerExecutor, SeverityFilter severityFilter)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<>c__DisplayClass87_0.<<Initialize>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.GetAnalyzerDriverFromPoolAsync(CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<>c__DisplayClass59_0.<<ComputeAnalyzerDiagnosticsAsync>g__getCompilationAndDriverAsync|0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.ComputeAnalyzerDiagnosticsAsync(AnalysisScope analysisScope, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.GetAnalysisResultCoreAsync(SourceOrAdditionalFile file, ImmutableArray`1 analyzers, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.GetAnalysisResultAsync(CompilationWithAnalyzers compilationWithAnalyzers, DocumentAnalysisScope documentAnalysisScope, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.GetAnalysisResultAsync(CompilationWithAnalyzers compilationWithAnalyzers, DocumentAnalysisScope documentAnalysisScope, Project project, DiagnosticAnalyzerInfoCache analyzerInfoCache, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.AnalyzeAsync(CompilationWithAnalyzers compilationWithAnalyzers, BidirectionalMap`2 analyzerToIdMap, ImmutableArray`1 analyzers, SkippedHostAnalyzersInfo skippedAnalyzersInfo, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetDiagnosticsAsync(IEnumerable`1 analyzerIds, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetNormalPriorityDiagnosticsAsync(IEnumerable`1 analyzerIds, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.<>c__DisplayClass4_0.<<CalculateDiagnosticsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.CalculateDiagnosticsAsync(Checksum solutionChecksum, DiagnosticArguments arguments, CancellationToken cancellationToken)
`
